project:
  type: website
  resources:
    - media/**

website:
  site-url: https://janna-and-ben.github.io
  navbar: 
    right:
      - text: "HOME"
        href: index.html
  #     - href: https://Janna-and-Ben.github.io/index.html
  #       text: ENGLISH
  #     - href: https://Janna-and-Ben.github.io/de/index.html
  #       text: DEUTSCH

format:
  html:
    theme: [cosmo, brand, styles.scss]
    include-after-body:
      - file: hero.html
    toc: false

lightbox: true

babelquarto:
  languagelinks: navbar
  languagecodes:
    - name: de
      text: "DEUTSCH"
    - name: en
      text: "ENGLISH"
  mainlanguage: en
  languages: 
    - de

lang: en

execute:
  echo: false
  warning: false
  error: false
